import type { Metadata } from 'next'

import { LegalPage, type LegalSection } from '@/components/landing/legal-page'

export const metadata: Metadata = {
  title: 'Terms of Service - Praxis',
  description:
    'The terms governing use of the Praxis platform, including acceptable use, availability, intellectual property, and liability.',
}

const SECTIONS: LegalSection[] = [
  {
    heading: 'Acceptable Use',
    body: [
      'You may use Praxis only for lawful business purposes, and only with data you have the right to process. This matters particularly for resumes and meeting recordings, where you are responsible for obtaining any consent the law requires.',
      'You may not attempt to bypass authentication or role restrictions, probe the platform for vulnerabilities without written authorisation, resell access, or use the service to generate unlawful, deceptive, or harassing content.',
      'You are responsible for activity under your account, including actions taken by workflows and scheduled jobs you configure.',
    ],
  },
  {
    heading: 'Service Level & Availability',
    body: [
      'We aim to keep Praxis available continuously, but the service is provided on an "as available" basis and may be interrupted by maintenance, provider outages, or events outside our control.',
      'Features that depend on third-party AI, storage, or email providers may degrade if those providers are unavailable. Formal uptime commitments, where offered, are set out in a separate written agreement.',
      'We may modify or discontinue features. Where a change materially reduces functionality you rely on, we will give reasonable notice to workspace administrators.',
    ],
  },
  {
    heading: 'Intellectual Property',
    body: [
      'Praxis and its underlying software, design, and documentation remain our property. These terms grant you a limited, non-exclusive, non-transferable right to use the service.',
      'You retain all rights to the content you upload. You grant us only the permissions needed to host, process, and display that content in order to operate the service for you.',
      'Output generated by the AI features is yours to use, subject to your responsibility to review it before relying on it.',
    ],
  },
  {
    heading: 'Subscription Terms',
    body: [
      'Paid plans are billed in advance on the cycle selected at purchase, and renew automatically until cancelled. Cancelling stops the next renewal; it does not retroactively refund the current period unless required by law.',
      'Usage allowances, such as monthly AI executions, are set by your plan. Exceeding them may result in throttling or a request to upgrade.',
      'We may revise pricing with reasonable notice before the change applies to your next renewal.',
    ],
  },
  {
    heading: 'Limitation of Liability',
    body: [
      'To the fullest extent permitted by law, Praxis is not liable for indirect, incidental, or consequential damages, or for lost profits, revenue, or data.',
      'Our total aggregate liability arising from the service is limited to the amounts you paid us in the twelve months preceding the claim.',
      'Nothing in these terms excludes liability that cannot lawfully be excluded.',
    ],
  },
  {
    heading: 'Account Termination',
    body: [
      'You may stop using Praxis and close your account at any time. We may suspend or terminate your access if you materially breach these terms, including the Acceptable Use provisions above, or if required to do so by law.',
      'Where reasonably possible, we will give notice before suspending or terminating an account for breach, and an opportunity to remedy the issue, except where immediate action is needed to protect the service or other users.',
      'On termination, your right to use the service ends immediately. Provisions that by their nature should survive termination - including Intellectual Property, Limitation of Liability, and this clause - remain in effect.',
    ],
  },
  {
    heading: 'Contact',
    body: ['Questions about these terms can be sent to hello@praxis.ai.'],
  },
]

export default function TermsOfServicePage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="January 2026"
      intro="These terms govern your use of the Praxis platform. By creating an account or using the service, you agree to them."
      sections={SECTIONS}
    />
  )
}
